
export const students = [
  {
    "id": 1,
    "name": "Alice Johnson",
    "age": 21,
    "course_id": 1,
    "username": "temp",
    "password": "123",
    "profile_pic": require('../assets/profilepic/1.jpg'),
    "address": "123 Maple Street, Springfield",
    "email": "alice.johnson@example.com",
    "phone": "555-123-4567",
    "gender": "Female",
    "blood_group": "O+"
  },
  {
    "id": 2,
    "name": "Bob Smith",
    "age": 22,
    "course_id": 2,
    "username": "bob.smith",
    "password": "securePass456",
    "profile_pic": require('../assets/profilepic/2.jpg'),
    "address": "456 Oak Avenue, Springfield",
    "email": "bob.smith@example.com",
    "phone": "555-234-5678",
    "gender": "Male",
    "blood_group": "A+"
  },
  {
    "id": 3,
    "name": "Charlie Brown",
    "age": 20,
    "course_id": 3,
    "username": "charlie.brown",
    "password": "securePass789",
    "profile_pic": require('../assets/profilepic/3.jpg'),
    "address": "789 Pine Road, Springfield",
    "email": "charlie.brown@example.com",
    "phone": "555-345-6789",
    "gender": "Male",
    "blood_group": "B+"
  },
  {
    "id": 4,
    "name": "Daisy Lee",
    "age": 23,
    "course_id": 4,
    "username": "daisy.lee",
    "password": "securePass101",
    "profile_pic": require('../assets/profilepic/4.jpg'),
    "address": "321 Birch Lane, Springfield",
    "email": "daisy.lee@example.com",
    "phone": "555-456-7890",
    "gender": "Female",
    "blood_group": "AB+"
  },
  {
    "id": 5,
    "name": "Evan Wright",
    "age": 19,
    "course_id": 1,
    "username": "evan.wright",
    "password": "securePass102",
    "profile_pic": require('../assets/profilepic/5.jpg'),
    "address": "654 Cedar Drive, Springfield",
    "email": "evan.wright@example.com",
    "phone": "555-567-8901",
    "gender": "Male",
    "blood_group": "O-"
  },
  {
    "id": 6,
    "name": "Fiona Carter",
    "age": 22,
    "course_id": 3,
    "username": "fiona.carter",
    "password": "securePass103",
    "profile_pic": require('../assets/profilepic/6.jpg'),
    "address": "987 Walnut Way, Springfield",
    "email": "fiona.carter@example.com",
    "phone": "555-678-9012",
    "gender": "Female",
    "blood_group": "B-"
  },
  {
    "id": 7,
    "name": "George Hall",
    "age": 21,
    "course_id": 2,
    "username": "george.hall",
    "password": "securePass104",
    "profile_pic": require('../assets/profilepic/7.jpg'),
    "address": "111 Aspen Court, Springfield",
    "email": "george.hall@example.com",
    "phone": "555-789-0123",
    "gender": "Male",
    "blood_group": "A-"
  },
  {
    "id": 8,
    "name": "Hannah Adams",
    "age": 20,
    "course_id": 4,
    "username": "hannah.adams",
    "password": "securePass105",
    "profile_pic": require('../assets/profilepic/8.jpg'),
    "address": "222 Willow Path, Springfield",
    "email": "hannah.adams@example.com",
    "phone": "555-890-1234",
    "gender": "Female",
    "blood_group": "AB-"
  },
  {
    "id": 9,
    "name": "Ian Baker",
    "age": 23,
    "course_id": 1,
    "username": "ian.baker",
    "password": "securePass106",
    "profile_pic": require('../assets/profilepic/9.jpg'),
    "address": "333 Elm Square, Springfield",
    "email": "ian.baker@example.com",
    "phone": "555-901-2345",
    "gender": "Male",
    "blood_group": "O+"
  },
  {
    "id": 10,
    "name": "Julia Davis",
    "age": 21,
    "course_id": 2,
    "username": "julia.davis",
    "password": "securePass107",
    "profile_pic": require('../assets/profilepic/10.jpg'),
    "address": "444 Cherry Circle, Springfield",
    "email": "julia.davis@example.com",
    "phone": "555-012-3456",
    "gender": "Female",
    "blood_group": "A+"
  },
  {
    "id": 11,
    "name": "Kevin Morris",
    "age": 22,
    "course_id": 3,
    "username": "kevin.m",
    "password": "P108",
    "profile_pic": require('../assets/profilepic/11.jpg'),
    "address": "555 Hickory Grove, Springfield",
    "email": "kevin.morris@example.com",
    "phone": "555-123-4567",
    "gender": "Male",
    "blood_group": "B+"
  },
  {
    "id": 12,
    "name": "Lila Turner",
    "age": 20,
    "course_id": 4,
    "username": "Lila.turner",
    "password": "securePass109",
    "profile_pic": require('../assets/profilepic/12.jpg'),
    "address": "666 Maple Avenue, Springfield",
    "email": "lila.turner@example.com",
    "phone": "555-234-5678",
    "gender": "Female",
    "blood_group": "AB+"
  },
  {
    "id": 13,
    "name": "Mason Clark",
    "age": 19,
    "course_id": 1,
    "username": "mason.clark",
    "password": "securePass110",
    "profile_pic": require('../assets/profilepic/13.jpg'),
    "address": "777 Birch Boulevard, Springfield",
    "email": "mason.clark@example.com",
    "phone": "555-345-6789",
    "gender": "Male",
    "blood_group": "O+"
  },
  {
    "id": 14,
    "name": "Nina Edwards",
    "age": 22,
    "course_id": 3,
    "username": "nina.edwards",
    "password": "securePass111",
    "profile_pic": require('../assets/profilepic/14.jpg'),
    "address": "888 Aspen Drive, Springfield",
    "email": "nina.edwards@example.com",
    "phone": "555-456-7890",
    "gender": "Female",
    "blood_group": "B+"
  },
  {
    "id": 15,
    "name": "Oliver Scott",
    "age": 21,
    "course_id": 4,
    "username": "oliver.scott",
    "password": "securePass112",
    "profile_pic": require('../assets/profilepic/15.jpg'),
    "address": "999 Elm Street, Springfield",
    "email": "oliver.scott@example.com",
    "phone": "555-567-8901",
    "gender": "Male",
    "blood_group": "A-"
  },
  {
    "id": 16,
    "name": "Paula White",
    "age": 23,
    "course_id": 2,
    "username": "paula.white",
    "password": "securePass113",
    "profile_pic": require('../assets/profilepic/16.jpg'),
    "address": "111 Willow Court, Springfield",
    "email": "paula.white@example.com",
    "phone": "555-678-9012",
    "gender": "Female",
    "blood_group": "AB-"
  },
  {
    "id": 17,
    "name": "Quinn Walker",
    "age": 20,
    "course_id": 1,
    "username": "quinn.walker",
    "password": "securePass114",
    "profile_pic": require('../assets/profilepic/17.jpg'),
    "address": "222 Cherry Lane, Springfield",
    "email": "quinn.walker@example.com",
    "phone": "555-789-0123",
    "gender": "Male",
    "blood_group": "O+"
  },
  {
    "id": 18,
    "name": "Rachel Young",
    "age": 21,
    "course_id": 3,
    "username": "rachel.young",
    "password": "securePass115",
    "profile_pic": require('../assets/profilepic/18.jpg'),
    "address": "333 Hickory Path, Springfield",
    "email": "rachel.young@example.com",
    "phone": "555-890-1234",
    "gender": "Female",
    "blood_group": "A+"
  }
];

export const healthTracks = [
  {
    "student_id": 1,
    "height": 165,
    "weight": 55,
    "last_checkup": "2023-07-15",
    "medical_conditions": ["None"],
    "heart_rate": 72,
    "blood_pressure": "120/80",
    "exercise_frequency": "Daily",
    "dietary_preference": "Vegetarian"
  },
  {
    "student_id": 2,
    "height": 178,
    "weight": 70,
    "last_checkup": "2023-06-20",
    "medical_conditions": ["Allergy - Pollen", "Mild Hypertension"],
    "heart_rate": 78,
    "blood_pressure": "135/85",
    "exercise_frequency": "Weekly",
    "dietary_preference": "Non-Vegetarian"
  },
  {
    "student_id": 3,
    "height": 172,
    "weight": 68,
    "last_checkup": "2023-08-05",
    "medical_conditions": ["Asthma", "Seasonal Allergies"],
    "heart_rate": 80,
    "blood_pressure": "130/85",
    "exercise_frequency": "Rarely",
    "dietary_preference": "Vegan"
  },
  {
    "student_id": 4,
    "height": 160,
    "weight": 50,
    "last_checkup": "2023-07-10",
    "medical_conditions": ["None"],
    "heart_rate": 68,
    "blood_pressure": "115/75",
    "exercise_frequency": "Daily",
    "dietary_preference": "Vegetarian"
  },
  {
    "student_id": 5,
    "height": 180,
    "weight": 75,
    "last_checkup": "2023-09-01",
    "medical_conditions": ["None"],
    "heart_rate": 76,
    "blood_pressure": "125/80",
    "exercise_frequency": "Never",
    "dietary_preference": "Non-Vegetarian"
  },
  {
    "student_id": 6,
    "height": 158,
    "weight": 48,
    "last_checkup": "2023-07-25",
    "medical_conditions": ["Iron Deficiency", "Low Blood Sugar"],
    "heart_rate": 70,
    "blood_pressure": "110/70",
    "exercise_frequency": "Rarely",
    "dietary_preference": "Others"
  },
  {
    "student_id": 7,
    "height": 175,
    "weight": 72,
    "last_checkup": "2023-08-15",
    "medical_conditions": ["High Blood Pressure"],
    "heart_rate": 82,
    "blood_pressure": "140/90",
    "exercise_frequency": "Weekly",
    "dietary_preference": "Non-Vegetarian"
  },
  {
    "student_id": 8,
    "height": 162,
    "weight": 54,
    "last_checkup": "2023-07-30",
    "medical_conditions": ["None"],
    "heart_rate": 74,
    "blood_pressure": "118/76",
    "exercise_frequency": "Daily",
    "dietary_preference": "Vegan"
  },
  {
    "student_id": 9,
    "height": 168,
    "weight": 65,
    "last_checkup": "2023-09-05",
    "medical_conditions": ["Migraines", "Vitamin D Deficiency"],
    "heart_rate": 75,
    "blood_pressure": "125/80",
    "exercise_frequency": "Never",
    "dietary_preference": "Non-Vegetarian"
  },
  {
    "student_id": 10,
    "height": 150,
    "weight": 60,
    "last_checkup": "2023-07-10",
    "medical_conditions": ["Seasonal Allergies"],
    "heart_rate": 72,
    "blood_pressure": "118/76",
    "exercise_frequency": "Weekly",
    "dietary_preference": "Vegetarian"
  },
  {
    "student_id": 11,
    "height": 178,
    "weight": 74,
    "last_checkup": "2023-06-28",
    "medical_conditions": ["Back Pain"],
    "heart_rate": 80,
    "blood_pressure": "130/85",
    "exercise_frequency": "Rarely",
    "dietary_preference": "Non-Vegetarian"
  },
  {
    "student_id": 12,
    "height": 160,
    "weight": 70,
    "last_checkup": "2023-08-02",
    "medical_conditions": ["Anemia"],
    "heart_rate": 68,
    "blood_pressure": "110/70",
    "exercise_frequency": "Never",
    "dietary_preference": "Vegan"
  },
  {
    "student_id": 13,
    "height": 182,
    "weight": 78,
    "last_checkup": "2023-09-18",
    "medical_conditions": ["None"],
    "heart_rate": 75,
    "blood_pressure": "120/80",
    "exercise_frequency": "Daily",
    "dietary_preference": "Vegetarian"
  },
  {
    "student_id": 14,
    "height": 165,
    "weight": 56,
    "last_checkup": "2023-07-22",
    "medical_conditions": ["Acne", "Allergy - Dust"],
    "heart_rate": 74,
    "blood_pressure": "118/76",
    "exercise_frequency": "Weekly",
    "dietary_preference": "Non-Vegetarian"
  },
  {
    "student_id": 15,
    "height": 176,
    "weight": 72,
    "last_checkup": "2023-08-10",
    "medical_conditions": ["None"],
    "heart_rate": 72,
    "blood_pressure": "120/80",
    "exercise_frequency": "Daily",
    "dietary_preference": "Vegetarian"
  },
  {
    "student_id": 16,
    "height": 162,
    "weight": 54,
    "last_checkup": "2023-07-05",
    "medical_conditions": ["Low Iron Levels", "Mild Depression"],
    "heart_rate": 70,
    "blood_pressure": "115/75",
    "exercise_frequency": "Rarely",
    "dietary_preference": "Others"
  },
  {
    "student_id": 17,
    "height": 180,
    "weight": 76,
    "last_checkup": "2023-09-12",
    "medical_conditions": ["None"],
    "heart_rate": 76,
    "blood_pressure": "125/80",
    "exercise_frequency": "Weekly",
    "dietary_preference": "Non-Vegetarian"
  },
  {
    "student_id": 18,
    "height": 158,
    "weight": 50,
    "last_checkup": "2023-07-18",
    "medical_conditions": ["Migraine", "Sinusitis"],
    "heart_rate": 78,
    "blood_pressure": "130/85",
    "exercise_frequency": "Daily",
    "dietary_preference": "Vegan"
  }
];